version: '3.1'

services:
  boleto_db:
    image: mysql:8.0.23
    restart: always
    container_name: container_mysql_bd_boletos
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306

  api:
    container_name: api
    image: node:16.14
    restart: always
    ports:
      - 3001:3001
      - 9229:9229
    user: node
    environment:
      - SQL_HOST=mysql
      - SQL_USERNAME=root
      - SQL_PASSWORD=1234
      - PORT=3001
    volumes:
      - ./:/app
    working_dir: /app
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i
    depends_on:
      - boleto_db
